config/routes.rb
Rails.application.routes.draw do
  root 'chats#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resources :chats, only: [:index, :create, :show]
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
  validates :body, presence: true
  after_create_commit :broadcast_message, :get_time

  def belongs_to_user?(user)
    if self.user.id == user.id
      true
    else
      false
    end
  end

  private
  def broadcast_message
    MessageBroadcastJob.perform_later(self)
  end

  def get_time
    @time_created = Time.now
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :chats, through: :subscriptions

  def name
    email.split('@')[0].capitalize!
  end

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map{ |sub| sub.user })
    end
    existing_chat_users.uniq
  end

  def msg_count(current_user)
    match = nil
    current_user.chats.each do |chat1|
      self.chats.each do |chat2|
        if chat1 == chat2
          match = chat1
        end
      end
    end
    if match
      match.messages.length
    else
      match
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
  before_action :require_login
  
  def index
    @existing_chats_users = current_user.existing_chats_users
    @other_users = User.all.select{|user| user.id != current_user.id}
  end

  def show
    @chat = Chat.find_by(id: params[:id])
    if @chat
      chat_users = @chat.subscriptions.map{|sub| sub.user.id}
      if !chat_users.include?(current_user.id)
        redirect_to root_path
        flash[:notice] = "Can't access private chat."
      end
      @other_user = User.find(params[:other_user])
      allowed = false
      chat_users.each do |user_id|
        if user_id == @other_user.id
          allowed = true
        end
      end
      if !allowed
        redirect_to root_path
        flash[:notice] = "You're not allowed to do that!"
      end
      @message = Message.new
    else
      redirect_to root_path
      flash[:notice] = "Woops, that chat doesn't exist."
    end
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat, :other_user => @other_user.id)
  end

  private
    def find_chat(other_user)
      my_chats_subs = []
      matching_subs = []
      current_user.chats.each do |chat|
        chat.subscriptions.each do |sub|
          my_chats_subs.push(sub)
        end
      end
      my_chats_subs.each do |sub|
        if sub.user.id == other_user.id
          matching_subs.push(sub)
        end
      end
      if matching_subs.first
        matching_subs.first.chat
      else
        false
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div id="chat-index">
  <div id="conversations">
    <h2>Active Conversations</h2>
      <% if @existing_chats_users.length > 0 %>
        <div class="conversation-list">
          <% @existing_chats_users.each do |other_user| %>
            <% if other_user != current_user %>
              <%= render 'users/user', user: other_user  %>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="conversation-list">
          <p class="no-active">No Conversations Yet</p>
        </div>
      <% end %>
  </div>

  <div id="friends">
    <h2>All Friends</h2>
    <div class="friends-list">
      <% if @other_users.length > 0 %>
        <%= render @other_users %>
      <% else %>
        <p class="no-active">Waiting for other users to sign up..</p>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<h1>Add New Chat</h1>

<%= form_for @chat do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name, autofocus: true %><br><br>

  <%= f.submit "Add!" %>
<% end %>
  

app/views/chats/show.html.erb
<p><%= link_to "Back to Chats", user_chats_path, class: 'back-btn' %></p>

<div class="chat-window">
  <h1><%= @other_user.name %></h1>
  
  <div id="chat-messages">
    <div id="messages" data-chat-id="<%= @chat.id %>">
      <% @chat.messages.each do |msg| %>
        <% if msg.user == current_user %>
          <%= render partial: 'messages/message', locals: { message: msg } %>
        <% else %>
          <%= render partial: 'messages/othermessage', locals: { message: msg } %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="message_form">
    <%= text_area_tag :message_body %>
    <button id="message_submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>  
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div id="navigation">
  <div class="nav-brand">
    <a href="/">
      <img src="https://bp-assets.biggerpockets.com/assets/logo/logo-1ac27e1791bcad86c95d3326c6c66a014be277075f97e9799825ba209612583a.svg" alt="biggerpockets" id="nav-logo-big">
      <%= image_tag 'bp-logo-sm.png', id: 'nav-logo-sm' %>
      Messenger
    </a>
  </div>
  <div class="nav-links">
    <% if signed_in? %>
      <p>Signed in as <%= current_user.name %> <i class="fa fa-hand-spock-o" aria-hidden="true"></i></p>
      <%= button_to 'Logout', sign_out_path, method: :delete, class: 'btn' %>
    <% else %>
      <%= link_to 'Login', sign_in_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="messenger-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-user">
    <i class="fa fa-user-circle fa-2x" aria-hidden="true"></i>
    <p><%= message.user.name %></p>
  </div>
  <div class="message-content">
    <p><%= message.body %></p>
  </div>
  <div class="message-timestamp">
    <p class="message-timestamp"><%= time_ago_in_words(message.created_at) %> ago</p>
  </div>
</div>

app/views/messages/_othermessage.html.erb
<div class="message">
  <div class="message-user other-user">
    <i class="fa fa-user-circle fa-2x" aria-hidden="true"></i>
    <p><%= message.user.name %></p>
  </div>
  <div class="message-content other-message-content">
    <p><%= message.body %></p>
  </div>
  <div class="message-timestamp other-message-timestamp">
    <p class="message-timestamp"><%= time_ago_in_words(message.created_at) %> ago</p>
  </div>
</div>

app/views/users/_form.html.erb
<p class="login-labels">Email</p>
<%= form.text_field :email, type: 'email' %>

<p class="login-labels">Password</p>
<%= form.password_field :password %>

app/views/users/_user.html.erb
<%= link_to(user_chats_path(current_user, :other_user => user.id), method: :post) do %>
  <div class="user">
    <%= user.name %>
    <% if user.msg_count(current_user) %>
      <div class="user-msg-count">
    <% else %>
      <div class="user-msg-count-hidden">
    <% end %>
        <%= user.msg_count(current_user) %>
      </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h1>Sign Up</h1>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
    
    <div class="other-links">
      <%= form.submit 'Sign Up', class: 'btn btn-lg btn-info' %>
    </div>
  <% end %>
</div>